SELECT FILTER_SEQ_ID.NEXTVAL FROM DUAL;
DELETE FROM AD_CODE_HIRE_FILTER;

SELECT FILTER_SEQ_ID.CURRVAL, 'DIRECT' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.AAD_REPORTING_MANAGER, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
FROM ADVP_AGENT_DETAILS_FIN AD
 WHERE LEVEL <= 2
START WITH AAD_AGENT_ID = UPPER('BR4291')
CONNECT BY PRIOR AAD_AGENT_ID = AAD_REPORTING_MANAGER;

SELECT * FROM AD_CODE_HIRE_FILTER WHERE SEQ_ID = '680';
SELECT AAD_AGENT_ID,AAD_REPORTING_MANAGER FROM ADVP_AGENT_DETAILS_FIN 
WHERE AAD_REPORTING_MANAGER = 'BR4690' AND AAD_CHANNEL_CODE = 'C000002';

SELECT * FROM ADVP_AGENT_DETAILS_FIN WHERE AAD_REPORTING_MANAGER = 'BT6969';

SELECT * FROM AD_CODE_HIRE_FILTER TAD
                    INNER JOIN (
                    SELECT AAD_AGENT_ID, MAX(POLICY_CNT) POLICY_CNT, MAX(DUEAMT) DUEAMT 
                                FROM USER_HIRA GROUP BY AAD_AGENT_ID
                                ) UH ON TAD.AD_CODE = UH.AAD_AGENT_ID
                                WHERE NVL(UH.POLICY_CNT,0) > 0 AND TAD.SEQ_ID = 833;
                                
SELECT  'UPLINK' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.UPLINE_MANGER_CODE, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
	FROM ADVP_AGENT_DETAILS_FIN AD
					LEFT JOIN AD_CODE_HIRE_FILTER FA ON AD.AAD_AGENT_ID = FA.AD_CODE AND FA.SEQ_ID = 828
				    WHERE LEVEL <= 4  AND FA.AD_CODE IS NULL
					START WITH AAD_AGENT_ID = UPPER('BR8092')
					CONNECT BY PRIOR AAD_AGENT_ID = UPLINE_MANGER_CODE;
                    
SELECT * FROM ADVP_AGENT_DETAILS_FIN;

		SELECT FILTER_SEQ_ID.CURRVAL, 'DIRECT' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.AAD_REPORTING_MANAGER, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
				FROM ADVP_AGENT_DETAILS_FIN AD
				    WHERE LEVEL <= 2
					START WITH AAD_AGENT_ID = UPPER('BR4690')
					CONNECT BY PRIOR AAD_AGENT_ID = AAD_REPORTING_MANAGER;

--OTHER THAN APC
		SELECT FILTER_SEQ_ID.CURRVAL, 'DIRECT' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.AAD_REPORTING_MANAGER, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
		FROM ADVP_AGENT_DETAILS_FIN AD
			START WITH AAD_AGENT_ID = UPPER('BP7740')
			CONNECT BY PRIOR AAD_AGENT_ID = AAD_REPORTING_MANAGER;
            
  SELECT
                    TOP_REPORTING_MANAGER AD_CODE  --TOP_REPORTING_MANAGER AD_CODE
                FROM AD_CODE_HIRE_FILTER TAD
                    INNER JOIN USER_HIRA UH ON TAD.AD_CODE = UH.AAD_AGENT_ID
                        AND UH.AAD_REPORTING_MANAGER IS NULL
                WHERE NVL(UH.POLICY_CNT,0) > 0 AND TAD.SEQ_ID = 833
                GROUP BY TAD.TOP_REPORTING_MANAGER;
            

 SELECT * FROM (
        SELECT /*+FIRST_ROWS(10)*/ROWNUM RNK,count(1) over () as ttl_rows,RECOMM.* 
        FROM
        (
            SELECT  RAD.AD_CODE AS BUSINESS_CODE
                , UPPER(DM.AMDD_DESIGNATION) as DESIGNATION
                , AD.AAD_NAME as NAME
                , RAD.POLICY as NO_OF_RENEWALS_DUE
                , RAD.AMOUNT TOTAL_RENEWAL_DUE
                , DECODE(AD.AAD_ROLECD,'R01','ADVISOR','R02','AGENT MANAGER','R03','SUPERVISOR') USER_ROLE  
--                , V_SEQ_ID SEQ
            FROM (
                SELECT
                    TAD.AD_CODE --TOP_REPORTING_MANAGER AD_CODE
                    , SUM(UH.POLICY_CNT) AS POLICY
                    , SUM(UH.DUEAMT) AS AMOUNT
                FROM AD_CODE_HIRE_FILTER TAD
                    INNER JOIN (SELECT AAD_AGENT_ID, MAX(POLICY_CNT) POLICY_CNT, MAX(DUEAMT) DUEAMT 
                                FROM USER_HIRA GROUP BY AAD_AGENT_ID
                                ) UH ON TAD.AD_CODE = UH.AAD_AGENT_ID
--                        AND UH.AAD_REPORTING_MANAGER IS NULL
                WHERE NVL(UH.POLICY_CNT,0) > 0 AND TAD.SEQ_ID = 573
                GROUP BY TAD.AD_CODE  --TAD.TOP_REPORTING_MANAGER
            ) RAD
            INNER JOIN ADVP_AGENT_DETAILS_FIN AD ON RAD.AD_CODE = AD.AAD_AGENT_ID
            INNER JOIN ADVP_DESIGNATION_MASTER DM ON DM.AMDD_DESIGNATION_CODE = AD.AAD_DESIGNATION_CODE
--            WHERE (UPPER(AD.AAD_NAME) LIKE NVL('%'||UPPER(P_SEARCH)||'%', UPPER(AD.AAD_NAME))
--                OR AD_CODE LIKE NVL('%'||UPPER(AD_CODE)||'%', AD_CODE))
--                AND UPPER(DM.AMDD_DESIGNATION) = NVL(P_DESIGINATION,UPPER(DM.AMDD_DESIGNATION))
        ) RECOMM
        ORDER BY NAME
        )
--          OFFSET ((P_PAGE_NO -1 ) * P_RECORDS_PER_PAGE) ROWS 
--           FETCH NEXT P_RECORDS_PER_PAGE ROWS ONLY     
        ;
        
        
	SELECT FILTER_SEQ_ID.CURRVAL, 'UPLINK' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.UPLINE_MANGER_CODE, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
				FROM ADVP_AGENT_DETAILS_FIN AD
					LEFT JOIN AD_CODE_HIRE_FILTER FA ON AD.AAD_AGENT_ID = FA.AD_CODE AND FA.SEQ_ID = 572
				    WHERE LEVEL <= 4 AND FA.AD_CODE IS NULL
					START WITH AAD_AGENT_ID = UPPER('BR4291')
					CONNECT BY PRIOR AAD_AGENT_ID = UPLINE_MANGER_CODE;
                    
select * from ADVP_AGENT_DETAILS_FIN where aad_agent_id = 'CA1090';

select * from USER_HIRA;

SELECT AAD_AGENT_ID,AAD_REPORTING_MANAGER ,CONNECT_BY_ROOT AAD_AGENT_ID,
SYS_CONNECT_BY_PATH(AAD_AGENT_ID,'->')PATH,LEVEL
FROM ADVP_AGENT_DETAILS_FIN
WHERE LEVEL <= 4
START WITH AAD_AGENT_ID = 'BR4291'
CONNECT BY PRIOR AAD_AGENT_ID = AAD_REPORTING_MANAGER
ORDER BY LEVEL;




				SELECT FILTER_SEQ_ID.CURRVAL, 'DIRECT' MANAGER_TYPE, AD.AAD_AGENT_ID, AD.AAD_REPORTING_MANAGER, CONNECT_BY_ROOT AAD_AGENT_ID, LEVEL
				FROM ADVP_AGENT_DETAILS_FIN AD
				    WHERE LEVEL <= 2
					START WITH AAD_AGENT_ID = UPPER(P_AD_CODE)
					CONNECT BY PRIOR AAD_AGENT_ID = AAD_REPORTING_MANAGER;
                    
            

 SELECT * FROM (
        SELECT /*+FIRST_ROWS(10)*/ROWNUM RNK,count(1) over () as ttl_rows,RECOMM.* 
        FROM
        (
            SELECT  RAD.AD_CODE AS BUSINESS_CODE
                , UPPER(DM.AMDD_DESIGNATION) as DESIGNATION
                , AD.AAD_NAME as NAME
                , RAD.POLICY as NO_OF_RENEWALS_DUE
                , RAD.AMOUNT TOTAL_RENEWAL_DUE
                , DECODE(AD.AAD_ROLECD,'R01','ADVISOR','R02','AGENT MANAGER','R03','SUPERVISOR') USER_ROLE  
--                , V_SEQ_ID SEQ
            FROM (
                SELECT
                    TOP_REPORTING_MANAGER AD_CODE --TOP_REPORTING_MANAGER AD_CODE
                    , SUM(UH.POLICY_CNT) AS POLICY
                    , SUM(UH.DUEAMT) AS AMOUNT
                FROM AD_CODE_HIRE_FILTER TAD
                    INNER JOIN (SELECT AAD_AGENT_ID, MAX(POLICY_CNT) POLICY_CNT, MAX(DUEAMT) DUEAMT 
                                FROM USER_HIRA GROUP BY AAD_AGENT_ID
                                ) UH ON TAD.AD_CODE = UH.AAD_AGENT_ID
--                        AND UH.AAD_REPORTING_MANAGER IS NULL
                WHERE NVL(UH.POLICY_CNT,0) > 0 AND TAD.SEQ_ID = 833
                GROUP BY TAD.TOP_REPORTING_MANAGER   --TAD.TOP_REPORTING_MANAGER
            ) RAD
            INNER JOIN ADVP_AGENT_DETAILS_FIN AD ON RAD.AD_CODE = AD.AAD_AGENT_ID
            INNER JOIN ADVP_DESIGNATION_MASTER DM ON DM.AMDD_DESIGNATION_CODE = AD.AAD_DESIGNATION_CODE
--            WHERE (UPPER(AD.AAD_NAME) LIKE NVL('%'||UPPER(P_SEARCH)||'%', UPPER(AD.AAD_NAME))
--                OR AD_CODE LIKE NVL('%'||UPPER(AD_CODE)||'%', AD_CODE))
--                AND UPPER(DM.AMDD_DESIGNATION) = NVL(P_DESIGINATION,UPPER(DM.AMDD_DESIGNATION))
        ) RECOMM
        ORDER BY NAME
        )
--          OFFSET ((P_PAGE_NO -1 ) * P_RECORDS_PER_PAGE) ROWS 
--           FETCH NEXT P_RECORDS_PER_PAGE ROWS ONLY     
        ;

                    
                    