CREATE TABLE TEMP_CUSTOMER_TB_DUB_20230817
AS
SELECT * FROM CUSTOMER_TB_DUB;

CREATE TABLE TEMP_POLICY_TB_DUB_20230817 
AS 
SELECT * FROM POLICY_TB_DUB

SELECT * FROM TEMP_CUSTOMER_TB_DUB_20230817;

ALTER TABLE TEMP_CUSTOMER_TB_DUB_20230817 ADD CONSTRAINT TEMP_CUSTOMER_TB_DUB_20230817_PK3 PRIMARY KEY (DUM_UID, AD_CODE);

CREATE INDEX IDX_TEMP_CUSTOMER_TB_DUB_20230817_NAME3 ON TEMP_CUSTOMER_TB_DUB_20230817
  (REPLACE(UPPER(NAME),' ',''));


ALTER TABLE TEMP_POLICY_TB_DUB_20230817 ADD CONSTRAINT TEMP_POLICY_TB_DUB_20230817_PK3 PRIMARY KEY (AD_CODE, POLICY_ID);



CREATE INDEX IDX_TEMP_DUM_UID_IDX2 ON TEMP_POLICY_TB_DUB_20230817 (DUM_UID);
CREATE INDEX IDX_TEMP_POLICY_TB_DUB_ADCODE_BRANCH_DUMID2 ON TEMP_POLICY_TB_DUB_20230817 (AD_CODE, CA_BRANCH_CODE, DUM_UID, PRODUCT_ID, POLICY_ID);
CREATE INDEX IDX_TEMP_POLICY_TB_DUB_BRANCHCODE2 ON TEMP_POLICY_TB_DUB_20230817 (CA_BRANCH_CODE);
CREATE INDEX IDX_TEMP_POLICY_TB_DUB_POLICY_STATUS2 ON TEMP_POLICY_TB_DUB_20230817 (TRIM(POLICY_STATUS_CODE), POLICY_ID);
CREATE INDEX IDX_TEMP_POLICY_TB_DUB_POLICY_STATUS_CODE2 ON TEMP_POLICY_TB_DUB_20230817 (POLICY_STATUS_CODE);
CREATE INDEX IDX_TEMP_POLICY_TB_DUB_PRODID2 ON TEMP_POLICY_TB_DUB_20230817 (PRODUCT_ID);
CREATE INDEX IDX_TEMP_PAYMENT_MODE2 ON TEMP_POLICY_TB_DUB_20230817 (PAYMENT_MODE);

















ALTER TABLE BKP_CUSTOMER_TB_DUB_20230801 ADD CONSTRAINT "BKP_CUSTOMER_TB_DUB_20230801_PK3" PRIMARY KEY ("DUM_UID", "AD_CODE");

 
  
  CREATE INDEX "IND15902"."IDX_BKP_CUSTOMER_TB_DUB_20230801_NAME3" ON "IND15902"."BKP_CUSTOMER_TB_DUB_20230801" 
  (REPLACE(UPPER("NAME"),' ',''));
  
  select * from all_indexes
  WHERE TABLE_NAME = 'BKP_CUSTOMER_TB_DUB_20230801';
  
  SELECT * FROM DM_CHANNEL_POLICIES;
  
  ALTER TABLE DM_CHANNEL_POLICIES ADD MODIFIED_DT DATE;
  UPDATE DM_CHANNEL_POLICIES SET MODIFIED_DT = SYSDATE - 5;
  
  ALTER TABLE DM_CHANNEL_POLICIES MODIFY MODIFIED_DT DATE DEFAULT SYSDATE NOT NULL;
  
   ALTER TABLE BANCA_BANK_BRANCE_POLICIES ADD MODIFIED_DT DATE;
  UPDATE BANCA_BANK_BRANCE_POLICIES SET MODIFIED_DT = SYSDATE - 5;
  
  ALTER TABLE BANCA_BANK_BRANCE_POLICIES MODIFY MODIFIED_DT DATE DEFAULT SYSDATE NOT NULL;
  
  SELECT * FROM BANCA_BANK_BRANCE_POLICIES;
  
  
  
     ALTER TABLE BANCA_CHANNEL_POLICIES ADD MODIFIED_DT DATE;
  UPDATE BANCA_CHANNEL_POLICIES SET MODIFIED_DT = SYSDATE - 5;
  
  ALTER TABLE BANCA_CHANNEL_POLICIES MODIFY MODIFIED_DT DATE DEFAULT SYSDATE NOT NULL;
  
  SELECT * FROM BANCA_CHANNEL_POLICIES;
  
  
  
  
  
  
  
  
  ------------------------------------------------------------------------------------
  
  SELECT JOB_NAME,STATUS,ACTUAL_START_DATE,ERROR#,RUN_DURATION AS Duration
FROM user_SCHEDULER_JOB_RUN_DETAILS
where  ACTUAL_START_DATE BETWEEN '21-AUG-23 09:45'
;

select * from user_SCHEDULER_JOB_RUN_DETAILS;

SELECT JOB_NAME,STATUS,ACTUAL_START_DATE,ERROR#,RUN_DURATION AS Duration
FROM user_SCHEDULER_JOB_RUN_DETAILS
where  ACTUAL_START_DATE like '%20-AUG-23%'
;
21-AUG-23 09.45.00.478810000 PM ASIA/CALCUTTA



SELECT DISTINCT JOB_NAME, STATUS, to_date(ACTUAL_START_DATE,'mm/dd/yyyy'),ERROR#,RUN_DURATION AS Duration
FROM USER_SCHEDULER_JOB_RUN_DETAILS
WHERE (EXTRACT(DAY FROM ACTUAL_START_DATE) >= 21 AND EXTRACT(DAY FROM ACTUAL_START_DATE) < 22)
ORDER BY ACTUAL_START_DATE ;
   
   
SELECT JOB_NAME, STATUS, TO_CHAR(ACTUAL_START_DATE,'MM/DD/YYYY') AS ACTUAL_START_DATE ,ERROR#,RUN_DURATION AS Duration
FROM USER_SCHEDULER_JOB_RUN_DETAILS
WHERE ACTUAL_START_DATE >= TO_DATE('2023-08-21 21:45:00', 'YYYY-MM-DD HH24:MI:SS') 
  AND ACTUAL_START_DATE <= TO_DATE('2023-08-22 09:00:00', 'YYYY-MM-DD HH24:MI:SS')
  ORDER BY ACTUAL_START_DATE;



SELECT
    JOB_NAME,
    STATUS,
    TO_CHAR(ACTUAL_START_DATE, 'MM/DD/YYYY') AS ACTUAL_START_DATE,
    RUN_DURATION AS Duration,
    ERROR#
FROM
    USER_SCHEDULER_JOB_RUN_DETAILS
WHERE
    ACTUAL_START_DATE >= TRUNC(SYSDATE) - 1 + (TO_DATE('21:45:00', 'HH24:MI:SS') - TRUNC(TO_DATE('21:45:00', 'HH24:MI:SS')))
    AND ACTUAL_START_DATE <= TRUNC(SYSDATE) + (TO_DATE('09:00:00', 'HH24:MI:SS') - TRUNC(TO_DATE('09:00:00', 'HH24:MI:SS')))
ORDER BY
    ACTUAL_START_DATE;
    
    SELECT
    JOB_NAME,
    STATUS,
    TO_CHAR(ACTUAL_START_DATE, 'MM/DD/YYYY') AS ACTUAL_START_DATE,
    SUBSTR(RUN_DURATION,5) AS Duration,
    ERROR#
FROM
    USER_SCHEDULER_JOB_RUN_DETAILS
WHERE
    ACTUAL_START_DATE >= TRUNC(SYSDATE) - 1 + (TO_DATE('21:45:00', 'HH24:MI:SS') - TRUNC(TO_DATE('21:45:00', 'HH24:MI:SS')))
    AND ACTUAL_START_DATE <= TRUNC(SYSDATE) + (TO_DATE('09:00:00', 'HH24:MI:SS') - TRUNC(TO_DATE('09:00:00', 'HH24:MI:SS')))
ORDER BY
    ACTUAL_START_DATE;
    
    

------------------------------------------------------------------------------------

SELECT
    JOB_NAME,
    STATUS,
    TO_CHAR(ACTUAL_START_DATE, 'MM/DD/YYYY') AS ACTUAL_START_DATE,
    SUBSTR(RUN_DURATION,5) AS Duration,
    ERROR#
FROM
    USER_SCHEDULER_JOB_RUN_DETAILS
WHERE
    ACTUAL_START_DATE >= TO_DATE(TO_CHAR(TRUNC(SYSDATE)-1,'YYYY-MM-DD') || ' 21:45:00'),'YYYY-MM-DD HH24:MI:SS')
    AND ACTUAL_START_DATE <= TO_DATE(TO_CHAR(TRUNC(SYSDATE),'YYYY-MM-DD') || ' 09:00:00'),'YYYY-MM-DD HH24:MI:SS')
    ACTUAL_START_DATE >= TRUNC(SYSDATE) - 1 + (TO_DATE('21:45:00', 'HH24:MI:SS') - TRUNC(TO_DATE('21:45:00', 'HH24:MI:SS')))
    AND ACTUAL_START_DATE <= TRUNC(SYSDATE) + (TO_DATE('09:00:00', 'HH24:MI:SS') - TRUNC(TO_DATE('09:00:00', 'HH24:MI:SS')))
ORDER BY
    ACTUAL_START_DATE;
    
    
    
    
    
  