BEGIN
   DBMS_AQADM.GRANT_QUEUE_PRIVILEGE(
      privilege     => 'ENQUEUE',
      queue_name    => 'C##TEST_USER3.queue_db1',
      grantee       => 'C##TEST_USER3',
      grant_option  => FALSE);
END;

GRANT EXECUTE ON DBMS_AQADM TO C##TEST_USER3;
GRANT EXECUTE ON DBMS_AQ TO C##TEST_USER3;
GRANT EXECUTE ON DBMS_AQADM TO C##TEST_USER4;
GRANT EXECUTE ON DBMS_AQ TO C##TEST_USER4;

REVOKE EXECUTE ON DBMS_AQADM FROM C##TEST_USER3;

SELECT * FROM DBA_OBJECTS
WHERE OBJECT_TYPE = upper('package')
AND OBJECT_NAME LIKE '%DBMS_AQADM%';