
create view view_table_names as
SELECT OWNER,table_name
FROM all_tables
WHERE TABLE_NAME IN (
  	'AAP_USER_POLICIES'
	,'AB_ADVISORAVATAR'
	,'AB_AUTHTOKENS'
	,'AB_OTP'
	,'AB_USERROLES'
	,'AB_USERSESSION'
	,'AB_WHATSAPPTOKEN'
	,'ADMIN_USERS'
	,'ADMIN_USERS_HISTORY'
	,'ADVP_ACCUMULATED_BONUS'
	,'ADVP_AGENT_CUSTOMER_MAPPING'
	,'ADVP_AGENT_DASHBOARD'
	,'ADVP_AGENT_DASHBOARD_1'
	,'ADVP_AGENT_DETAILS'
	,'ADVP_AGENT_DETAILS_FIN'
	,'ADVP_AGENT_DETAILS_TEST'
	,'ADVP_AGENT_GLOBAL_SEARCH_HISTORY'
	,'ADVP_CAMPAIGNCHANNEL_FILEINFO'
	,'ADVP_CAMPAIGNCHANNEL_FILEINFO_H'
	,'ADVP_CAMPAIGNCHANNEL_UPLOAD'
	,'ADVP_CAMPAIGNCHANNEL_UPLOAD_H'
	,'ADVP_COMMISSION_ADJUSTMENT_DETAIL'
	,'ADVP_COMMISSION_ADJUSTMENT_DETAILS'
	,'ADVP_COMMISSION_DETAIL'
	,'ADVP_COMMISSION_ONHOLD'
	,'ADVP_COMMISSION_PAYOUTPOLICYINDIVIDUAL'
	,'ADVP_COMMISSION_SUMMARY'
	,'ADVP_COMM_DETAILS_HIST'
	,'ADVP_CUSTOMER_MASTER'
	,'ADVP_CUSTOMER_SEARCH_HISTORY'
	,'ADVP_CUSTOMER_SERVICE_REQUEST'
	,'ADVP_CUSTOMER_SERVICE_REQUEST_MAPPING_CODE'
	,'ADVP_DESIGNATION_MASTER'
	,'ADVP_GLOBAL_SEARCH_POLICY_STATUS'
	,'ADVP_INCREMENTAL_TABLE_DETAILS'
	,'ADVP_INTIMATED_TO_CUSTOMER'
	,'ADVP_LOV_PENDING_REQUIREMENT'
	,'ADVP_LOV_WAIVER_TYPE'
	,'ADVP_NONGC_USER_LOG'
	,'ADVP_OLD_COMM_DETAILS'
	,'ADVP_OLD_COMM_DETAILS_HIST'
	,'ADVP_POLICYWISE_EARNING'
	,'ADVP_POLICY_DETAILS'
	,'ADVP_POLICY_DISPATCH_REPORT'
	,'ADVP_POLICY_STATUS_ADVISOR_MAPPING'
	,'ADVP_POLICY_STATUS_BYDATE_FILTER'
	,'ADVP_POLICY_STATUS_BYDATE_FILTER_GROUP_MAPPING'
	,'ADVP_POLICY_STATUS_GROUP_MASTER'
	,'ADVP_POLICY_WISE_AUM'
	,'ADVP_PRODUCT_MASTER'
	,'ADVP_REPORTEE_ALL_DATA'
	,'ADVP_REPORTEE_ALL_DATA_BANCA_CHANNEL'
	,'ADVP_REPORTEE_RENEWAL_INFO_DATA'
	,'ADVP_REVIVAL_FILTERS_NEWTEST'
	,'ADVP_RNR_CLOSED_CONTEST'
	,'ADVP_RNR_CONTEST_DETAILS_ADMIN'
	,'ADVP_RNR_CONTEST_DETAILS_ADMIN_HISTORY'
	,'ADVP_RNR_CONTEST_MASTER'
	,'ADVP_RNR_CONTEST_SUMMARY'
	,'ADVP_RNR_CONTEST_SUMMARY_POLIWISE_DTS'
	,'ADVP_RNR_PAST_CONTEST'
	,'ADVP_ROLE_MASTER'
	,'ADVP_STAGING_COMMCYCLE_DUMP'
	,'ADVP_STAGING_ROTOSP_DUMP'
	,'ADVP_STAGING_TCLI_DUMP'
	,'ADVP_STAGING_TCVG_DUMP'
	,'ADVP_STAGING_TEDIT_DUMP'
	,'ADVP_STAGING_TPOLC_DUMP'
	,'ADVP_STAGING_TPREG_DUMP'
	,'ADVP_STAGING_TP_FILE'
	,'ADVP_STAGING_TRIWV_DUMP'
	,'ADVP_TCAMPAIGNMASTERDETAILS'
	,'ADVP_UPDATE_LOG'
	,'ADVP_USER_ROLE_MASTER'
	,'AD_CD_JSON'
	,'AD_POLICY_PAID_STATUS'
	,'AP_AGENT_PROFILE_CHANGE_REQUEST'
	,'AUM_DUB'
	,'BANCA_BANK_BRANCE_POLICIES'
	,'BIRTHDAY_ACTION_CARD_DAILY'
	,'CUSTOMER_TB_DUB'
	,'CUST_POL_CD_TB'
	,'DAILY_BIRTHDAY_LISTING'
	,'DAILY_PAYMENT_OVERDUE'
	,'DM_POLICIES'
	,'DORY_STAGING_GETAGENTDETAIL_UPDATE_DUMP_NEW'
	,'DORY_STAGING_GETSPDATA_UPDATE_DUMP_NEW'
	,'DORY_STAGING_TPREG_DUMP_NEW'
	,'ENACH_TXN_DETAILS'
	,'FAMILY_TAG'
	,'HDFC_POLICIES'
	,'LOG_HLFALLBACKJOB'
	,'LOG_TMASTERTABLEINFO'
	,'LOG_TSPINPUTPARAMS'
	,'LOG_TSPINPUTPARAMS_CAMPAINGNBULKUPLOAD'
	,'LOG_TSPINPUTPARAMS_COMMISSION_SUMMARY_PAGE'
	,'LOG_TSPINPUTPARAMS_COMMI_CONSOLIDATED_STATEMENT'
	,'MOBILE_SSO_TB'
	,'NEMO_ADVISOR_FEEDBACK'
	,'NEMO_INSURED_DETAILS'
	,'NEMO_LOV_BILLING_METHOD'
	,'NEMO_LOV_POLICY_STATUS'
	,'NEMO_NOMINEE_DETAILS'
	,'NEMO_STAGING_AGENT_DETAILS_DUMP'
	,'NEMO_STAGING_COMM_VW_ADJUSTMENTDETAILS_01'
	,'NEMO_STAGING_GETAGENTDETAIL_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETAGENTHIERARCHY_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETAGENTLEVEL_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETONEDOWNHIERARCHY_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETPARTNERBRANCH_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETSPDATA_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_GETSPDETAILS_UPDATE_INCREMENTAL'
	,'NEMO_STAGING_IDA_SS_CODES_DUMP'
	,'NEMO_STAGING_IDA_SS_CODE_INCREMENT'
	,'NEMO_STAGING_PAYMENT_DUMP'
	,'NEMO_STAGING_PAYOUTPOLICYCORPORATE_01'
	,'NEMO_STAGING_PAYOUTPOLICYINDIVIDUAL_01'
	,'NEMO_STAGING_PRODUCT_MIX_DUMP'
	,'NEMO_STAGING_REVERSE_FEED_OP_01'
	,'NEMO_STAGING_TAG_DUMP'
	,'NEMO_STAGING_TBNDV_DUMP'
	,'NEMO_STAGING_TBNDV_INCREMENT'
	,'NEMO_STAGING_TCHQV_DUMP'
	,'NEMO_STAGING_TCLEP_DUMP'
	,'NEMO_STAGING_TCLIA_DUMP'
	,'NEMO_STAGING_TCLIC_01'
	,'NEMO_STAGING_TCLIC_DUMP'
	,'NEMO_STAGING_TCLI_01'
	,'NEMO_STAGING_TCLI_DUMP'
	,'NEMO_STAGING_TCLNM_DUMP'
	,'NEMO_STAGING_TCVG_DUMP'
	,'NEMO_STAGING_TEDIT_DUMP'
	,'NEMO_STAGING_TFD_DUMP'
	,'NEMO_STAGING_TMDDD_01'
	,'NEMO_STAGING_TORPH_01'
	,'NEMO_STAGING_TPH_DUMP'
	,'NEMO_STAGING_TPOLC_01'
	,'NEMO_STAGING_TPOLC_DUMP'
	,'NEMO_STAGING_TPOL_01'
	,'NEMO_STAGING_TPOL_01_HDFC'
	,'NEMO_STAGING_TPOL_DUMP'
	,'NEMO_STAGING_TPREG_01'
	,'NEMO_STAGING_TPREG_DUMP'
	,'NEMO_STAGING_TP_FILE_01'
	,'NEMO_STAGING_TRANSACTION_REVERSE_FEED_01'
	,'NEMO_STAGING_TRCP2_01_HDFC'
	,'NEMO_STAGING_TRCP_DUMP'
	,'NEMO_STAGING_TREQP_01'
	,'NEMO_STAGING_VW_ADJUSTMENTDETAILS_01'
	,'NEMO_STAGING_VW_AGENTCYCLESUMMARY_01'
	,'NEMO_STAGING_VW_RNR_LEDGER_01'
	,'NEMO_STAGING_VW_USMBRANCHMAP_DUMP_NEW'
	,'OTP_LOG'
	,'PAYMENT_ACTION_CARD_DAILY'
	,'POLICY_ACTION_CARD_DAILY'
	,'POLICY_ORD_STATUS_CODE'
	,'POLICY_STATEMENT_COUNT'
	,'POLICY_TB_DUB'
	,'PREMIUM_TB_DUB'
	,'PRODUCT_TB'
	,'PRODUCT_TB_DUB'
	,'RNR_EXPIRE'
	,'TEMP_DP_CUSTOMER_TB_DUB'
	,'TEMP_DP_CUSTOMER_UPDATE'
	,'TEMP_DP_POLICY_MAP'
	,'TEMP_DP_POLICY_TB_DUB'
	,'TPD_POLICIES'
	,'USERSESSION_INPUT'
	,'USER_HIRA'
	,'USER_HIRA_BANCA'
);

select * from view_table_names;

--list of the table column ,owner,table_name,datatype,data_length and nullable
SELECT tn.OWNER,tn.TABLE_NAME,t.column_name,t.data_type,t.data_length,t.nullable
FROM view_table_names tn
JOIN ALL_TAB_COLUMNS t
on tn.table_name = t.table_name
order by tn.table_name,t.column_name;


--PROCEDURES
select proc.object_name as procedure_name,
       args.argument_name,
       args.in_out,
       args.data_type,
       args.data_length,
       proc.owner as schema_name
from all_procedures proc
left join all_arguments args
    on proc.object_id = args.object_id
where proc.owner  in ('IND15901','IND16801','IND15902','IND15903')
      and object_type = 'PROCEDURE'
order by schema_name,
         procedure_name,
         args.position;

--common procedure list
select proc.object_name as procedure_name,
       args.argument_name,
       args.in_out,
       args.data_type,
       args.data_length,
       proc.owner as schema_name
from all_procedures proc
left join all_arguments args
    on proc.object_id = args.object_id
where proc.object_name in (
    'P_NEMO_AP_CUSTOMER_LIST',
'P_NEMO_AP_CUSTOMER_ADD_RMV_FAMILY',
'P_NEMO_AP_POLICY_STATEMENT_DOWNLOAD_COUNT',
'P_NEMO_SP_POLICY_STATEMENT_DOWNLOAD_COUNT',
'P_NEMO_AP_CUSTOMER_FAMILY_VIEW',
'P_NEMO_AP_CUSTOMER_SERVICE_REQUEST_GET_DETAILS',
'P_NEMO_AP_PORTFOLIO_POLICY_STATUS',
'P_NEMO_AP_POLICY_DETAILS_STATUS',
'P_NEMO_AP_PAYMENT_OVERDUE',
'AP_AUTHTOKENS',
'AP_USERSESSIONS',
'P_NEMO_AP_RECOMM_CAMPAIGN_DOWNLOAD',
'P_NEMO_AP_ACTION_CARD_CTA_UPDATES',
'P_NEMO_AP_BIRTHDAY_LISTING',
'TESTING_RNR_AGENT_MGR_CONTEST_LISTING',
'P_NEMO_AP_RECOMM_CAMPAIGN',
'P_NEMO_AP_UPDATING_PAYMENT_BIRTHDAY_LINK',
'P_NEMO_AP_ALL_CUSTOMER_PRODUCT_LIST',
'JOB_SDAILYFEEDBACK',
'P_NEMO_AP_POLICY_DISPATCH_REPORT',
'P_NEMP_AP_POLICY_STATEMENT_GET_DETAIL',
'P_NEMO_AP_COMMISSION_PAYOUTCYCLE',
'P_NEMO_AP_RNR_AGENT_MGR_CONTEST_WISE_LIST',
'P_NEMO_AP_RNR_AGENT_MGR_CONTEST_LIST_DOWNLOAD',
'P_NEMO_AP_RENEWAL_LISTING',
'P_NEMO_AP_ALL_CUSTOMERS',
'P_NEMO_CAMPAINGNBULKUPLOAD',
'P_NEMO_AP_ALL_CUSTOMER_FAV_ADD_RMV',
'P_NEMO_AP_RNR_RUNNING_CONTEST_LISTING',
'P_NEMO_AP_RNR_COLSED_CONTEST_LISTING',
'P_NEMO_AP_PAYMENT_PAID',
'TEST_AGENT',
'P_NEMO_AP_REPORTEEDETAIL',
'P_NEMO_AP_RNR_CONTEST_DETAILS_ADVISOR',
'P_NEMO_AGEN_MANAGER_OR_SUPERVISORS_DASHBOARD_NOTIFY',
'P_NEMO_AP_RECOMM_PREAPPROVED_OFFERS_LISTING',
'AP_ADMIN_USERS',
'P_NEMO_AP_NON_GC_FLAG',
'P_NEMO_AP_COMMISSION_SUMMARY_PAGE',
'AP_ADMIN_USERS_HISTORY',
'P_NEMO_AP_ADVISOR_AGENTT_DASHBOARD',
'P_NEMO_AP_RECOMM_RETENTION',
'P_NEMO_AP_DAILY_UPDATED_COUNT',
'GET_COLUMN_COMPARASION',
'GET_COLUMNS_FOR_TABLE',
'P_NEMO_AP_REVIVAL_LIST',
'P_CAMPAIGN_FILEINFO',
'P_NEMO_AP_COMMISSION_POTENTIAL_EARNING',
'P_NEMO_AP_ENACH_DETAILS',
'P_MOBILE_SSO',
'P_NEMO_AP_RNR_CONTEST_DETAILS_ADMIN',
'P_NEMO_AP_MANAGER_RENEWAL',
'P_NEMO_INCREMENTAL_TABLES_CREATION_JOB',
'P_NEMO_AP_AGENT_GLOBAL_SEARCH_LISTING',
'P_NEMO_AP_AGENT_GLOBAL_SAVE_SEARCH_RESULT',
'P_NEMO_AP_AGENT_GLOBAL_REMOVE_SEARCH',
'P_NEMO_AP_AGENT_GLOBAL_RECENT_SEARCH',
'P_NEMO_AP_CONTEST_SUMMARY_POLI_WISE_DTS',
'P_CAMPAIGNUPLOADCHECK',
'TESTING_ALL_CUSTOMERS',
'P_NEMO_INCREMENTAL_TABLES_JOBS_2',
'P_NEMO_INCREMENTAL_TABLES_JOBS_3',
'P_NEMO_AP_COMMI_CONSOLIDATED_STATEMENT',
'PROCEDURE8',
'P_NEMO_AP_REVIVAL_LIST_DWLD',
'P_NEMO_AP_PAYMENT_OVERDUE_DOWNLOAD',
'TESTING_AGENT_GLOBAL_SEARCH_LISTING',
'P_NEMO_AP_CUSTOMER_GET_FVT_FLAG',
'P_NEMO_AP_CONTEST_SUMMARY',
'P_NEMO_AP_AGENT_DROPDOWN_SEARCH',
'AP_WHATSAPPTOKENS',
'AP_OTP',
'P_NEMO_AP_AGENT_BIRTHDAY_LISTING',
'P_NEMO_AP_AGENT_LISTING',
'P_NEMO_AP_COMMISSION_LISTING',
'AP_UPLOADAVATAR',
'CREATE_AUDIT_TABLES',
'CREATE_AUDIT_TRIGGERS',
'P_NEMO_AP_REQ_DOWNLOAD_XSL',
'P_NEMO_AP_ALL_CUSTOMERS_CS417021',
'P_NEMO_AP_POLICY_DETAIL_POLICY_STATUS',
'P_NEMO_AP_MYSELF_COMMI_PAID_DETAIL',
'JOB_SDAILYGATRACKER',
'JOB_SDAILYUSERLOGIN',
'P_NEMO_AP_AGENT_PROFILE_CHANGE_REQUEST',
'P_NEMO_AP_RNR_CONTEST_EXPIRY',
'TESTING_ALL_CUSTOMERS_DOWNLOAD',
'TESTING_RENEWAL_LISTING',
'P_NEMO_AP_RNR_AGENT_MGR_CONTEST_LISTING',
'P_NEMO_ADVISOR_FEEDBACK',
'P_NEMO_AGEN_MANAGER_OR_SUPERVISORS_DASHBOARD',
'P_NEMO_AP_AGENT_STAFF_TWC',
'P_NEMO_AP_AGENT_MANAGER_DETAILS',
'P_NEMO_AP_CONTEST_SUMMARY_RUNNING_CLOSED_REPORT',
'P_NEMO_AP_CUSTOMER_SERVICE_REQUEST',
'P_NEMO_AP_RNR_DASHBOARD',
'JOB_SDAILY_RNR_EXPIRY',
'P_NEMO_AP_RNR_RESULT_AWAITED_CONTEST',
'JOB_SDAILYMAILSCHEDULER',
'P_NEMO_AP_ALL_CUSTOMERS_DOWNLOAD',
'P_NEMO_AP_ACCUMULATED_BONUS',
'P_NEMO_AP_POLICY_DETAILS_STATUS_DAILY_LOG',
'P_DAILY_BIRTHDAY_JOB',
'P_NEMO_AP_COMMISSION_SUMMARY_PAGE_NEW',
'P_NEMO_AP_ALL_CUSTOMERS_DOWNLOAD_BCK',
'P_NEMO_AP_GA_SERVICE_TRACKING',
'AD_CD_DUP_REMOVE',
'GET_POL_CUST_DETAILS',
'P_NEMO_AP_RENEWAL_LISTING_DOWNLOAD',
'P_NEMO_AP_ALL_CUSTOMERS_BCK',
'PROCEDURE6',
'P_NEMO_AP_RECOMM_RETENTION_251121',
'P_NEMO_AP_ENACH_TRANSACTION_DETAILS',
'P_NEMO_INCREMENTAL_JOB_HL_FALLBACK_MASTER',
'P_NEMO_INCREMENTAL_JOB_HL_FALLBACK_TABLES',
'P_NEMO_INCREMENTAL_OTHER_CHANNELS_UPDATE_JOB',
'FN_RENEWALVIEW_TOTAL',
'FN_RENEWALVIEW_CNT',
'P_NEMO_REPORTEE_RENEWAL_JOB',
'P_NEMO_AP_RNR_CONTEST_ADMIN_VIEW',
'LOG_SS3INFO',
'P_NEMO_INCREMENTAL_JOB_TBNDV',
'P_NEMO_INCREMENTAL_JOB_RNR_BATCH',
'P_NEMO_INCREMENTAL_TABLES_JOBS_RNR',
'P_NEMO_INCREMENTAL_TABLES_JOBS_ENACH',
'P_NEMO_INCREMENTAL_TABLES_JOBS_1',
'AP_AGENT_DASHBOARD_JOB_SCHEDULER',
'P_NEMO_REPORTEEDETAIL_INC',
'P_NEMO_AP_REPORTEEDETAIL_DEMO',
'TESTING_CUSTOMER_LIST',
'TEST_PROC',
'P_NEMO_AP_CUSTOMER_RECENT_SEARCH',
'TRIGGER1',
'TRIGGER_CUSTOMER_TB_DUB'
)
and object_type = 'PROCEDURE'
order by schema_name,
         procedure_name,
         args.position;
         
         
--INDEXES
SELECT ind.index_name,
       ind.table_name,
       ind.uniqueness,
       ind.index_type,
       col.column_name,
       ind.owner AS schema_name
FROM all_indexes ind
   left JOIN all_ind_columns col
    ON ind.owner = col.index_owner
    AND ind.index_name = col.index_name
WHERE ind.owner IN ('IND15901','IND16801','IND15902','IND15903')
      AND ind.table_owner NOT LIKE 'SYS%'
ORDER BY schema_name,
         table_name,
         index_name,
         column_position;
         
--functions
SELECT func.object_name AS function_name,
       args.argument_name,
       args.data_type,
       args.in_out,
       func.status,
       args.data_length,
       func.owner AS schema_name
FROM all_objects func
     JOIN all_arguments args
    ON func.object_id = args.object_id
WHERE func.owner IN ('IND15901','IND16801','IND15902','IND15903')
      AND func.object_type = 'FUNCTION'
ORDER BY function_name;







select * from all_source where owner = 'IND15901' AND NAME = 'AP_AGENT_DASHBOARD_JOB_SCHEDULER';
select text from all_source
where owner = 'IND15901'
and name = 'P_NEMO_AP_COMMISSION_SUMMARY_PAGE';
--procedures
select owner,object_name from all_procedures 
where owner in ('IND16801','IND15902','IND15901','IND15903');

--triggers
select owner,trigger_name,trigger_type,table_owner,table_name from all_triggers 
where owner in ('IND16801','IND15902','IND15901','IND15903');

--indexes
select owner,index_name,index_type,table_name,table_owner,uniqueness from all_indexes
where owner in('IND16801','IND15902','IND15901','IND15903');

--views
select * from all_views
where owner in ('IND16801','IND15902','IND15901','IND15903');

--sequences
select sequence_owner,sequence_name from all_sequences
where sequence_owner in ('IND16801','IND15902','IND15901','IND15903');


--FUNCTIONS
select object_name,status,owner from all_objects 
where object_type = upper('FUNCTION')
and owner in ('IND16801','IND15902','IND15901','IND15903');



select object_name,object_type from all_objects
where owner = 'IND16801'
ORDER BY OBJECT_TYPE;

SELECT OWNER,TABLE_NAME FROM ALL_TABLES
WHERE OWNER IN ('IND16801','IND15902','IND15901','IND15903');








select * from all_tab_columns where table_name = 'NEMO_STAGING_CHM_AGENT_M_01';
select * from NEMO_STAGING_CHM_AGENT_M_01;
select channel_code from NEMO_STAGING_IDA_SS_CODE_DUMP_AAP_USER where channel_code = 'C000001';


select * from all_tab_columns where table_name = 'nemo_staging_getspdata_update_dump';

select * from all_tab_columns where column_name =upper('channel_code');
and column_name = upper('status_code') ;

select * from all_users;
select * from v$session;

select table_name from all_tables where upper(channel_code) = 'C000001' and upper(status_code) = upper('terminated');

select * from all_tab_columns where column_name = upper('channel_code') and exists
( select * from all_tab_columns where column_name = upper('status_code'));


select * from all_tab_columns where column_name = upper('status_code');
select * from all_tab_columns where table_name = 'NEMO_STAGING_RNR_REVERSE_FEED_OP';

select * from all_tab_columns where table_name = 'DBA_LOGSTDBY_EVENTS';